--AGENCY_RESPONSES

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."AGENCY_RESPONSES" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID" from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Formal Response to Questions';



--BIOPHARMACEUTIC_STUDIES_271


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."BIOPHARMACEUTIC_STUDIES_271" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID" from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Summary of Biopharmaceutic Studies and Analytical Methods';



--BRIEFING_DOCUMENT

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."BRIEFING_DOCUMENT" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID" 
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where a.business_unit = 'Pharma' and CLASSIFICATION_DOMAIN ='Regulatory' and a.document_status = 'Internally Approved' and document_language = 'English' and (classification_group = 'Agency Meetings' or classification_group is null) and STATUS_LAST_UPDATED >= '1-AUG-2022';


--Clinical_Overview_252

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."Clinical_Overview_252" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Clinical Overview';



--Clinical_Pharmacology_Studies_272

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."Clinical_Pharmacology_Studies_272" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID" 
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Summary of Clinical Pharmacology Studies';



--CSR


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."CSR" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Study Report Body Text';




--CTA_Component


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."CTA_Component" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where a.business_unit = 'Pharma' and classification_domain = 'Clinical'

 and a.document_status = 'Internally Approved' and STATUS_LAST_UPDATED >='1-AUG-2022';

 
 
 
 
 --DEVELOPMENT_SAFETY_UPDATE_REPORT
 
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."DEVELOPMENT_SAFETY_UPDATE_REPORT" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select   a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL               

 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Development Safety Update Report (DSUR)';




--PERIODIC_SAFETY_UPDATE_REPORT

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."PERIODIC_SAFETY_UPDATE_REPORT" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'http://uw00016ek:8080/cara/drl/objectId/' || a.r_object_id || ''    AS Document_URL                 


 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Periodic Safety Update Report (PSUR)';



--PIPS_PSPS

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."PIPS_PSPS" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Pediatric Information';





--VW_FINALIB

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_FINALIB" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "STUDY_PHASE", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name,b.study_phase
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,r_creation_date,
'http://uw00016ek:8080/cara/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select 
"R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","STUDY_PHASE","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Final IB';




--VW_PROTOCOL

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_PROTOCOL" ("R_OBJECT_ID", "BUSINESS_UNIT", "IN_VD_WORKFLOW", "DOCUMENT_NAME", "DOCUMENT_STATUS", "FULL_TITLE", "ECTD_TITLE", "STATUS_LAST_UPDATED", "R_MODIFY_DATE", "CLASSIFICATION_DOMAIN", "CLASSIFICATION_SUBGROUP", "CLASSIFICATION_GROUP", "CLASSIFICATION_ARTIFACT", "MARKET_NAME", "ORIGINATOR_COUNTRY_NAME", "DOCUMENT_LANGUAGE", "IS_ACTIVE", "DRUG_SUBSTANCE_NAME", "GENERIC_NAME_INN", "INDICATION_NAME", "STUDY_NUMBER", "PRODUCT_FAMILY_NAME", "R_CREATION_DATE", "STUDY_PHASE", "DOCUMENT_URL", "DOCUMENT_R_OBJECT_ID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  with first_view as (
select     a.r_object_id,  Business_UNIT,          
IN_VD_WORKFLOW,
Object_name Document_Name,
Document_status,
FULL_TITLE,
ECTD_TITLE ,

STATUS_LAST_UPDATED,
R_MODIFY_DATE ,CLASSIFICATION_DOMAIN  ,
CLASSIFICATION_subgroup,
CLASSIFICATION_group,
classification_artifact,
MARKET_NAME,
ORIGINATOR_COUNTRY_NAME,
DOCUMENT_LANGUAGE,
IS_ACTIVE,
drug_substance_name
,GENERIC_NAME_INN ,indication_name,study_number,product_family_name,a.r_creation_date,b.study_phase,
'http://uw00016ek:8080/cara/drl/objectId/' || a.r_object_id || ''    AS Document_URL
 from COSMOSDBEXPORT.document a
inner join COSMOSDBEXPORT.document_r b on a.r_object_id = b.document_r_object_id),

second_view as (
select document_r_object_id from COSMOSDBEXPORT.document_r where r_version_label like '%CURRENT%'
)

select "R_OBJECT_ID","BUSINESS_UNIT","IN_VD_WORKFLOW","DOCUMENT_NAME","DOCUMENT_STATUS","FULL_TITLE","ECTD_TITLE","STATUS_LAST_UPDATED","R_MODIFY_DATE","CLASSIFICATION_DOMAIN","CLASSIFICATION_SUBGROUP","CLASSIFICATION_GROUP","CLASSIFICATION_ARTIFACT","MARKET_NAME","ORIGINATOR_COUNTRY_NAME","DOCUMENT_LANGUAGE","IS_ACTIVE","DRUG_SUBSTANCE_NAME","GENERIC_NAME_INN","INDICATION_NAME","STUDY_NUMBER","PRODUCT_FAMILY_NAME","R_CREATION_DATE","STUDY_PHASE","DOCUMENT_URL","DOCUMENT_R_OBJECT_ID"
from first_view a
inner join second_view b on a.r_object_id = b.document_r_object_id
where CLASSIFICATION_SUBGROUP  = 'Protocol and Protocol Amendments';
