
--VW_ACT_CCDS


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_ACT_CCDS" ("ACT_R_OBJECT_ID", "ACT_NAME", "ACT_CONFIG_UID", "ACT_FULL_DESCRIPTION", "ACT_PRODUCT_FAMILY_NAME", "ACT_PRODUCT_FAMILY_UID", "ACT_CLASSIFICATION_GROUP", "ACT_CLASSIFICATION_SUBGROUP", "ACT_CLASSIFICATION_ARTIFACT", "ACT_CCDS_CHANGE_DESCRIPTION", "ACT_CCDS_CHA_IMPLEMENTATION", "ACT_CCDS_CHANGE_TYPE", "ACT_CHANGE_NUMBER", "ACT_SAFETY_SIGNAL_NUMBER", "ACT_IS_CCDS", "ACT_CCDS_DISTRIBUTION_DATE", "ACT_TARGET_COMPLETION_DATE", "ACT_SIGNAL_CONFIRMATION_DATE", "ACT_ELABELLING_DATE", "ACT_IS_ELABELLING_IMPACTD", "ACT_SUBMISSION_PLANNED_DATE", "ACT_FIRST_SUBMISSION_DATE", "ACT_AGENCY_APPROVAL_DATE", "ACT_AGENCY_APPROVAL_STATUS", "ACT_R_MODIFY_DATE", "ACT_R_CREATION_DATE", "ACT_REG_APPLICATION_NAME", "ACT_REG_APPLICATION_UID", "ACT_MEDICINAL_PRODUCT_NAME", "ACT_MEDICINAL_PRODUCT_UID", "ACT_REVIEWING_MARKET_NAME", "ACT_REVIEWING_MARKET_UID") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  (SELECT DISTINCT
                MGR.R_OBJECT_ID ACT_R_OBJECT_ID,
                MGR.OBJECT_NAME ACT_NAME,
                MGR.CONFIG_UID ACT_CONFIG_UID,
                MGR.FULL_DESCRIPTION ACT_FULL_DESCRIPTION,
                SUBMGR_B.PRODUCT_FAMILY_NAME ACT_PRODUCT_FAMILY_NAME,
                SUBMGR_B.PRODUCT_FAMILY_UID ACT_PRODUCT_FAMILY_UID,
                --SUBMGR_RR.GLOBAL_PRODUCT_UID ACT_GLOBAL_PRODUCT_UID,
                ---ACT_MRKT.MARKET_NAME ACT_MARKET_NAME,
                ---ACT_MRKT.MARKET_UID ACT_MARKET_UID,
                MGR.CLASSIFICATION_GROUP ACT_CLASSIFICATION_GROUP,
                MGR.CLASSIFICATION_SUBGROUP ACT_CLASSIFICATION_SUBGROUP,
                MGR.CLASSIFICATION_ARTIFACT ACT_CLASSIFICATION_ARTIFACT,
                ACT_CHNG.CCDS_CHANGE_DESCRIPTION ACT_CCDS_CHANGE_DESCRIPTION,
                ACT_CHNG.CCDS_CHANGE_IMPLEMENTATION
                   ACT_CCDS_CHA_IMPLEMENTATION,
                ACT_CHNG.CCDS_CHANGE_TYPE ACT_CCDS_CHANGE_TYPE,
                ACT_CHNG.CHANGE_NUMBER ACT_CHANGE_NUMBER,
                ACT_CHNG.SAFETY_SIGNAL_NUMBER ACT_SAFETY_SIGNAL_NUMBER,
                ACT_CHNG.IS_CCDS ACT_IS_CCDS,
                MGR.CCDS_DISTRIBUTION_DATE ACT_CCDS_DISTRIBUTION_DATE,
                MGR.TARGET_COMPLETION_DATE ACT_TARGET_COMPLETION_DATE,
                -- SUBMGR_RR.GLOBAL_PRODUCT_NAME ACT_GLOBAL_PRODUCT_NAME,
                --  SUBMGR_RR.GLOBAL_PRODUCT_UID ACT_GLOBAL_PRODUCT_UID,
                ---SUBMGR_RR.ASSEMBLY_ID ACT_ASSEMBLY_ID,
                -- SUBMGR_RR.LINKED_ACTIVITY_NAME ACT_LINKED_ACTIVITY_NAME,
                -- SUBMGR_RR.LINKED_ACTIVITY_UID ACT_LINKED_ACTIVITY_UID,
                ACT_CHNG.SIGNAL_CONFIRMATION_DATE ACT_SIGNAL_CONFIRMATION_DATE,
                MGR.EXTERNAL_APPROVAL_DATE ACT_ELABELLING_DATE,
                MGR.IS_REG_LABELING_IMPACTED ACT_IS_ELABELLING_IMPACTD,
                (SELECT MAX (SUBMISSION_PLANNED_DATE)
                   FROM COSMOSDBEXPORT.DOCUMENT a
                  WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly' --and CLASSIFICATION_SUBGROUP='Main Assembly'
                        --- AND a.I_CHRONICLE_ID = SUBMGR_R.ASSEMBLY_ID
                        AND a.R_OBJECT_ID = SUBMGR_RR.ASSEMBLY_ID
                        AND SUBMISSION_PLANNED_DATE IS NOT NULL)
                   ACT_SUBMISSION_PLANNED_DATE,
                MGR.FIRST_SUBMISSION_DATE ACT_FIRST_SUBMISSION_DATE,
                MGR.AGENCY_APPROVAL_DATE ACT_AGENCY_APPROVAL_DATE,
                MGR.AGENCY_APPROVAL_STATUS ACT_AGENCY_APPROVAL_STATUS,
				MGR.R_MODIFY_DATE ACT_R_MODIFY_DATE,
				MGR.R_CREATION_DATE ACT_R_CREATION_DATE,
				SUBMGR_B.REGULATORY_APPLICATION_NAME ACT_REG_APPLICATION_NAME,
				SUBMGR_B.REGULATORY_APPLICATION_UID ACT_REG_APPLICATION_UID,
				SUBMGR_B.MEDICINAL_PRODUCT_NAME ACT_MEDICINAL_PRODUCT_NAME,
				SUBMGR_B.MEDICINAL_PRODUCT_UID ACT_MEDICINAL_PRODUCT_UID,
				MGR.REVIEWING_MARKET_NAME ACT_REVIEWING_MARKET_NAME,
                MGR.REVIEWING_MARKET_UID ACT_REVIEWING_MARKET_UID
           FROM COSMOSDBEXPORT.SUBMISSION_MANAGER MGR,
                COSMOSDBEXPORT.REGULATORY_ACTIVITY ACT,
                /*(SELECT DISTINCT SUBMISSION_MANAGER_R_OBJECT_ID,
                                 r_index,
                                 MARKET_NAME,
                                 market_UID
                   FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_B
                  WHERE --- SUBMISSION_MANAGER_R_OBJECT_ID='0800f9f6851b6082' and
                        MARKET_NAME IS NOT NULL) ACT_MRKT,*/
                TBL_INTR_ACT_CCDS ACT_CHNG,
                COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_RR,
                (  SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                          MAX (PRODUCT_FAMILY_NAME) PRODUCT_FAMILY_NAME,
                          MAX (PRODUCT_FAMILY_UID) PRODUCT_FAMILY_UID,
						  MAX (REGULATORY_APPLICATION_NAME) REGULATORY_APPLICATION_NAME,
                          MAX (REGULATORY_APPLICATION_UID) REGULATORY_APPLICATION_UID,
						  MAX(MEDICINAL_PRODUCT_NAME) MEDICINAL_PRODUCT_NAME,
						  MAX(MEDICINAL_PRODUCT_UID) MEDICINAL_PRODUCT_UID
                     FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_B
                    WHERE ---SUBMISSION_MANAGER_R_OBJECT_ID='0800f9f6851b6082' AND
 /*   SUBMGR_B.CCDS_CHANGE_TYPE IN
              ('Critical Safety', 'Other Safety')
     AND*/
                          PRODUCT_FAMILY_NAME IS NOT NULL
                 GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID) SUBMGR_B
          WHERE     MGR.R_OBJECT_ID = ACT.R_OBJECT_ID
                ---AND MGR.R_OBJECT_ID='0800f9f6851b6082'
               --- AND MGR.R_OBJECT_ID = ACT_MRKT.SUBMISSION_MANAGER_R_OBJECT_ID(+)
                AND MGR.R_OBJECT_ID = SUBMGR_B.SUBMISSION_MANAGER_R_OBJECT_ID
                AND MGR.R_OBJECT_ID =
                       SUBMGR_RR.SUBMISSION_MANAGER_R_OBJECT_ID
                AND MGR.R_OBJECT_ID =
                       ACT_CHNG.SUBMISSION_MANAGER_R_OBJECT_ID(+));




--VW_EVENT_CCDS

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_EVENT_CCDS" ("EVNT_R_OBJECT_ID", "EVNT_EVENT_NAME", "EVNT_CONFIG_UID", "EVNT_FULL_DESCRIPTION", "EVNT_PRODUCT_FAMILY_NAME", "EVNT_PRODUCT_FAMILY_UID", "EVNT_MARKET_NAME", "EVNT_MARKET_UID", "EVNT_CLASSIFICATION_GROUP", "EVNT_CLASSIFICATION_SUBGROUP", "EVNT_CLASSIFICATION_ARTIFACT", "EVNT_CCDS_CHANGE_DESCRIPTION", "EVNT_CCDS_CHA_IMPLEMENTATION", "EVNT_CCDS_CHANGE_TYPE", "EVNT_CHANGE_NUMBER", "EVNT_SAFETY_SIGNAL_NUMBER", "EVNT_IS_CCDS", "EVNT_CCDS_DISTRIBUTION_DATE", "EVNT_TARGET_COMPLETION_DATE", "EVNT_GLOBAL_PRODUCT_NAME", "EVNT_GLOBAL_PRODUCT_UID", "EVNT_ASSEMBLY_ID", "EVNT_LINKED_ACTIVITY_NAME", "EVNT_LINKED_ACTIVITY_UID", "EVNT_SIGNAL_CONFIRMATION_DATE", "EVNT_ELABELLING_DATE", "EVNT_SUBMISSION_PLANNED_DATE", "EVNT_VERSION_NUMBER", "EVNT_CCDS_APPROVAL_DATE", "EVNT_SPL_SAFETY_SIGNAL_NUMBER", "REFERENCE_MARKET_NAME", "REFERENCE_MARKET_UID", "REVIEWING_MARKET_NAME", "REVIEWING_MARKET_UID", "EVNT_R_MODIFY_DATE", "EVNT_R_CREATION_DATE") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  (SELECT MGRM.R_OBJECT_ID EVNT_R_OBJECT_ID,
                MGRM.OBJECT_NAME EVNT_EVENT_NAME,
                MGRM.CONFIG_UID EVNT_CONFIG_UID,
                MGRM.FULL_DESCRIPTION EVNT_FULL_DESCRIPTION,
                SUBMGR_R.PRODUCT_FAMILY_NAME EVNT_PRODUCT_FAMILY_NAME,
                SUBMGR_R.PRODUCT_FAMILY_UID EVNT_PRODUCT_FAMILY_UID,
                SUBMGR_R.MARKET_NAME EVNT_MARKET_NAME,
                SUBMGR_R.MARKET_UID EVNT_MARKET_UID,
                MGRM.CLASSIFICATION_GROUP EVNT_CLASSIFICATION_GROUP,
                MGRM.CLASSIFICATION_SUBGROUP EVNT_CLASSIFICATION_SUBGROUP,
                MGRM.CLASSIFICATION_ARTIFACT EVNT_CLASSIFICATION_ARTIFACT,
                SUBMGR_R.CCDS_CHANGE_DESCRIPTION EVNT_CCDS_CHANGE_DESCRIPTION,
                SUBMGR_R.CCDS_CHANGE_IMPLEMENTATION
                   EVNT_CCDS_CHA_IMPLEMENTATION,
                SUBMGR_R.CCDS_CHANGE_TYPE EVNT_CCDS_CHANGE_TYPE,
                SUBMGR_R.CHANGE_NUMBER EVNT_CHANGE_NUMBER,
                SUBMGR_R.S_SAFETY_SIGNAL_NUMBER EVNT_SAFETY_SIGNAL_NUMBER,
                SUBMGR_R.IS_CCDS EVNT_IS_CCDS,
                MGRM.CCDS_DISTRIBUTION_DATE EVNT_CCDS_DISTRIBUTION_DATE,
                MGRM.TARGET_COMPLETION_DATE EVNT_TARGET_COMPLETION_DATE,
                SUBMGR_R.GLOBAL_PRODUCT_NAME EVNT_GLOBAL_PRODUCT_NAME,
                SUBMGR_R.GLOBAL_PRODUCT_UID EVNT_GLOBAL_PRODUCT_UID,
                SUBMGR_R.ASSEMBLY_ID EVNT_ASSEMBLY_ID,
                SUBMGR_R.LINKED_ACTIVITY_NAME EVNT_LINKED_ACTIVITY_NAME,
                SUBMGR_R.LINKED_ACTIVITY_UID EVNT_LINKED_ACTIVITY_UID,
                SUBMGR_R.SIGNAL_CONFIRMATION_DATE EVNT_SIGNAL_CONFIRMATION_DATE,
                MGRM.EXTERNAL_APPROVAL_DATE EVNT_ELABELLING_DATE,
                (SELECT MAX (SUBMISSION_PLANNED_DATE)
                   FROM COSMOSDBEXPORT.DOCUMENT a
                  WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly' 
                        AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                        AND SUBMISSION_PLANNED_DATE IS NOT NULL)
                   EVNT_SUBMISSION_PLANNED_DATE,
                (SELECT MAX (VERSION_NUMBER)
                   FROM COSMOSDBEXPORT.DOCUMENT a
                  WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly'
                        AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                        AND VERSION_NUMBER IS NOT NULL)
                   EVNT_VERSION_NUMBER,
                (SELECT MAX (CCDS_APPROVAL_DATE)
                   FROM COSMOSDBEXPORT.DOCUMENT a
                  WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly' 
                        AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                        AND CCDS_APPROVAL_DATE IS NOT NULL)
                   EVNT_CCDS_APPROVAL_DATE,
                SUBMGR_R.SPLITTED_SAFETY_SIGNAL_NUMBER
                   evnt_SPL_SAFETY_SIGNAL_NUMBER,
                MGRM.REFERENCE_MARKET_NAME,
                MGRM.REFERENCE_MARKET_UID,
                MGRM.REVIEWING_MARKET_NAME,
                MGRM.REVIEWING_MARKET_UID,
				MGRM.R_MODIFY_DATE EVNT_R_MODIFY_DATE,
				MGRM.R_CREATION_DATE EVNT_R_CREATION_DATE
           FROM (SELECT MGR.*
                   FROM COSMOSDBEXPORT.SUBMISSION_MANAGER MGR,
                        COSMOSDBEXPORT.REGULATORY_EVENT EVNT
                  WHERE     MGR.R_OBJECT_ID = EVNT.R_OBJECT_ID
                        AND MGR.classification_subgroup IN ('Labeling')
                        AND CLASSIFICATION_ARTIFACT = 'CCDS') MGRM,
                (SELECT SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID,
                        SUBMGR_B.PRODUCT_FAMILY_NAME,
                        SUBMGR_B.PRODUCT_FAMILY_UID,
                        SUBMGR_C.CCDS_CHANGE_DESCRIPTION,
						SUBMGR_C.SIGNAL_CONFIRMATION_DATE,
                        SUBMGR_C.CCDS_CHANGE_IMPLEMENTATION,
                        SUBMGR_C.CCDS_CHANGE_TYPE,
                        SUBMGR_C.CHANGE_NUMBER,
                        SUBMGR_C.S_SAFETY_SIGNAL_NUMBER,
                        SUBMGR_C.IS_CCDS,
                        SUBMGR_B.GLOBAL_PRODUCT_NAME,
                        SUBMGR_B.GLOBAL_PRODUCT_UID,
                        SUBMGR_A.LINKED_EVENT_NAME,
                        SUBMGR_A.LINKED_EVENT_UID,
                        SUBMGR_A.MARKET_NAME,
                        SUBMGR_A.MARKET_UID,
                        SUBMGR_A.RESPONSIBLE_PERSON,
                        SUBMGR_A.RESPONSIBLE_PERSON_ID,
                        SUBMGR_A.AGENCY_RESPONSE_DATE,
                        SUBMGR_BA.ASSEMBLY_ID,
                        SUBMGR_A.LINKED_ACTIVITY_NAME,
                        SUBMGR_A.LINKED_ACTIVITY_UID,
                        SUBMGR_C.SAFETY_SIGNAL_NUMBER
                           SPLITTED_SAFETY_SIGNAL_NUMBER
                   FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_A,(SELECT SUBMISSION_MANAGER_R_OBJECT_ID, MAX(ASSEMBLY_ID) ASSEMBLY_ID
                             FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_IB
                            WHERE exists (select 1 from COSMOSDBEXPORT.DOCUMENT a
									WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly' 
										AND a.R_OBJECT_ID = SUBMGR_IB.ASSEMBLY_ID) AND ASSEMBLY_ID iS NOT NULL GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID)
                          SUBMGR_BA,
                        (  SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                  MAX (PRODUCT_FAMILY_NAME) PRODUCT_FAMILY_NAME,
                                  MAX (PRODUCT_FAMILY_UID) PRODUCT_FAMILY_UID,
								  MAX (GLOBAL_PRODUCT_NAME) GLOBAL_PRODUCT_NAME,
                                  MAX (GLOBAL_PRODUCT_UID) GLOBAL_PRODUCT_UID
                             FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_B
                            WHERE 
                                  PRODUCT_FAMILY_NAME IS NOT NULL
                         GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID) SUBMGR_B,
                         TBL_INTR_EVNT_CCDS SUBMGR_C
                  WHERE     SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_B.SUBMISSION_MANAGER_R_OBJECT_ID
					    AND SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_BA.SUBMISSION_MANAGER_R_OBJECT_ID(+)
                        AND SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_C.SUBMISSION_MANAGER_R_OBJECT_ID --AND SUBMGR_A.R_INDEX=SUBMGR_C.R_INDEX
 ---AND SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID=SUBMGR_D.SUBMISSION_MANAGER_R_OBJECT_ID
                ) SUBMGR_R
          WHERE MGRM.R_OBJECT_ID = SUBMGR_R.SUBMISSION_MANAGER_R_OBJECT_ID ---and SUBMGR_R.PRODUCT_FAMILY_NAME='upadacitinib'
                                                                          ----AND SUBMGR_R.MARKET_NAME='Colombia'
        );


		
--VW_CCDS_RPT		
		
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_CCDS_RPT" ("BS_ACT_ID", "BS_EVNT_UID", "EVNT_R_OBJECT_ID", "EVNT_EVENT_NAME", "EVNT_CONFIG_UID", "EVNT_FULL_DESCRIPTION", "EVNT_PRODUCT_FAMILY_NAME", "EVNT_PRODUCT_FAMILY_UID", "EVNT_MARKET_NAME", "EVNT_MARKET_UID", "EVNT_CLASSIFICATION_GROUP", "EVNT_CLASSIFICATION_SUBGROUP", "EVNT_CLASSIFICATION_ARTIFACT", "EVNT_CCDS_CHANGE_DESCRIPTION", "EVNT_CCDS_CHA_IMPLEMENTATION", "EVNT_CCDS_CHANGE_TYPE", "EVNT_CHANGE_NUMBER", "EVNT_SAFETY_SIGNAL_NUMBER", "EVNT_IS_CCDS", "EVNT_CCDS_DISTRIBUTION_DATE", "EVNT_TARGET_COMPLETION_DATE", "EVNT_GLOBAL_PRODUCT_NAME", "EVNT_ASSEMBLY_ID", "EVNT_LINKED_ACTIVITY_NAME", "EVNT_LINKED_ACTIVITY_UID", "EVNT_SIGNAL_CONFIRMATION_DATE", "EVNT_ELABELLING_DATE", "EVNT_SUBMISSION_PLANNED_DATE", "EVNT_VERSION_NUMBER", "EVNT_CCDS_APPROVAL_DATE", "EVNT_SPL_SAFETY_SIGNAL_NUMBER", "EVNT_R_MODIFY_DATE", "EVNT_R_CREATION_DATE", "ACT_R_OBJECT_ID", "ACT_NAME", "ACT_CONFIG_UID", "ACT_FULL_DESCRIPTION", "ACT_PRODUCT_FAMILY_NAME", "ACT_PRODUCT_FAMILY_UID", "ACT_CLASSIFICATION_GROUP", "ACT_CLASSIFICATION_SUBGROUP", "ACT_CLASSIFICATION_ARTIFACT", "ACT_CCDS_CHANGE_DESCRIPTION", "ACT_CCDS_CHA_IMPLEMENTATION", "ACT_CCDS_CHANGE_TYPE", "ACT_CHANGE_NUMBER", "ACT_SAFETY_SIGNAL_NUMBER", "ACT_IS_CCDS", "ACT_CCDS_DISTRIBUTION_DATE", "ACT_TARGET_COMPLETION_DATE", "ACT_SIGNAL_CONFIRMATION_DATE", "ACT_ELABELLING_DATE", "ACT_IS_ELABELLING_IMPACTD", "ACT_SUBMISSION_PLANNED_DATE", "ACT_FIRST_SUBMISSION_DATE", "ACT_AGENCY_APPROVAL_DATE", "ACT_AGENCY_APPROVAL_STATUS", "ACT_R_MODIFY_DATE", "ACT_R_CREATION_DATE", "ACT_REG_APPLICATION_NAME", "ACT_REG_APPLICATION_UID", "ACT_MEDICINAL_PRODUCT_NAME", "ACT_MEDICINAL_PRODUCT_UID", "ACT_REVIEWING_MARKET_NAME", "ACT_REVIEWING_MARKET_UID", "ROSTER_REGION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  (SELECT DISTINCT ACT_MAIN."BS_ACT_ID",
      
                ACT_MAIN."BS_EVNT_UID",
                 EVNT_R_OBJECT_ID,
                 EVNT_EVENT_NAME,
                 EVNT_CONFIG_UID,
                 EVNT_FULL_DESCRIPTION,
                 EVNT_PRODUCT_FAMILY_NAME,
                 EVNT_PRODUCT_FAMILY_UID,
                 --   EVNT_GLOBAL_PRODUCT_UID,
                 EVNT_MARKET_NAME,
                 EVNT_MARKET_UID,
                 EVNT_CLASSIFICATION_GROUP,
                 EVNT_CLASSIFICATION_SUBGROUP,
                 EVNT_CLASSIFICATION_ARTIFACT,
                 EVNT_CCDS_CHANGE_DESCRIPTION,
                 EVNT_CCDS_CHA_IMPLEMENTATION,
                 EVNT_CCDS_CHANGE_TYPE,
                 EVNT_CHANGE_NUMBER,
                 EVNT_SAFETY_SIGNAL_NUMBER,
                 EVNT_IS_CCDS,
                 EVNT_CCDS_DISTRIBUTION_DATE,
                 EVNT_TARGET_COMPLETION_DATE,
                 EVNT_GLOBAL_PRODUCT_NAME,
                 --   EVNT_GLOBAL_PRODUCT_UID,
                 EVNT_ASSEMBLY_ID,
                 EVNT_LINKED_ACTIVITY_NAME,
                 EVNT_LINKED_ACTIVITY_UID,
                 EVNT_SIGNAL_CONFIRMATION_DATE,
                 EVNT_ELABELLING_DATE,
                 EVNT_SUBMISSION_PLANNED_DATE,
                 EVNT_VERSION_NUMBER,
                 EVNT_CCDS_APPROVAL_DATE,
                 evnt_SPL_SAFETY_SIGNAL_NUMBER,
				 EVNT_R_MODIFY_DATE,
				 EVNT_R_CREATION_DATE,
                 ACT_MAIN."ACT_R_OBJECT_ID",
                 ACT_MAIN."ACT_NAME",
                 ACT_MAIN."ACT_CONFIG_UID",
                 ACT_MAIN."ACT_FULL_DESCRIPTION",
                 ACT_MAIN."ACT_PRODUCT_FAMILY_NAME",
                 ACT_MAIN."ACT_PRODUCT_FAMILY_UID",
                 --ACT_MAIN."ACT_MARKET_NAME",
                 --ACT_MAIN."ACT_MARKET_UID",
                 ACT_MAIN."ACT_CLASSIFICATION_GROUP",
                 ACT_MAIN."ACT_CLASSIFICATION_SUBGROUP",
                 ACT_MAIN."ACT_CLASSIFICATION_ARTIFACT",
                 ACT_MAIN."ACT_CCDS_CHANGE_DESCRIPTION",
                 ACT_MAIN."ACT_CCDS_CHA_IMPLEMENTATION",
                 ACT_MAIN."ACT_CCDS_CHANGE_TYPE",
                 ACT_MAIN."ACT_CHANGE_NUMBER",
                 ACT_MAIN."ACT_SAFETY_SIGNAL_NUMBER",
                 ACT_MAIN."ACT_IS_CCDS",
                 ACT_MAIN."ACT_CCDS_DISTRIBUTION_DATE",
                 ACT_MAIN."ACT_TARGET_COMPLETION_DATE",
                 ACT_MAIN."ACT_SIGNAL_CONFIRMATION_DATE",
                 ACT_MAIN."ACT_ELABELLING_DATE",
                 ACT_MAIN."ACT_IS_ELABELLING_IMPACTD",
                 ACT_MAIN."ACT_SUBMISSION_PLANNED_DATE",
                 ACT_MAIN."ACT_FIRST_SUBMISSION_DATE",
                 ACT_MAIN."ACT_AGENCY_APPROVAL_DATE",
                 ACT_MAIN."ACT_AGENCY_APPROVAL_STATUS",
				 ACT_MAIN.ACT_R_MODIFY_DATE,
				ACT_MAIN.ACT_R_CREATION_DATE,
				ACT_MAIN.ACT_REG_APPLICATION_NAME,
			    ACT_MAIN.ACT_REG_APPLICATION_UID,
				ACT_MAIN.ACT_MEDICINAL_PRODUCT_NAME,
				ACT_MAIN.ACT_MEDICINAL_PRODUCT_UID,
				ACT_MAIN.ACT_REVIEWING_MARKET_NAME,
                ACT_MAIN.ACT_REVIEWING_MARKET_UID,
                m.roster_region
   
   FROM (select * from VW_EVENT_CCDS RPT where  EXISTS (select 1 from  COSMOSDBEXPORT.SUBMISSION_MANAGER_R where 
						SUBMISSION_MANAGER_R_OBJECT_ID=RPT.EVNT_R_OBJECT_ID and R_VERSION_LABEL='CURRENT')) evnt_o,
                        (select BS_ACT_ID,BS_EVNT_UID,ACT.* from VW_ACT_CCDS ACT,TBL_labeling_lnkg ACT_LNKG where  ACT.ACT_R_OBJECT_ID=ACT_LNKG.BS_ACT_ID) ACT_MAIN
                        ,cosmosdbexport.market m
   WHERE evnt_o.EVNT_CONFIG_UID = ACT_MAIN.BS_EVNT_UID(+)
  --- AND evnt_event_name='carbidopa and levodopa - september-2019 - major' ---and evnt_market_name in ('Saudi Arabia','Kuwait','Qatar')
       --- AND ACT_LNKG.BS_ACT_ID = ACT_MAIN.ACT_R_OBJECT_ID
        ---AND ACT_LNKG.BS_ACT_ID='0800f9f686053a42'
        AND EVNT_MARKET_NAME = ACT_REVIEWING_MARKET_NAME(+)
        AND EVNT_MARKET_NAME = m.iso_country_name(+)
        AND EVNT_CCDS_CHANGE_DESCRIPTION = nvl(ACT_CCDS_CHANGE_DESCRIPTION,EVNT_CCDS_CHANGE_DESCRIPTION));

		
		
--VW_EVENT_F6
  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_EVENT_F6" ("EVNT_R_OBJECT_ID", "EVNT_EVENT_NAME", "EVNT_CONFIG_UID", "EVNT_FULL_DESCRIPTION", "EVNT_PRODUCT_FAMILY_NAME", "EVNT_PRODUCT_FAMILY_UID", "EVNT_MARKET_NAME", "EVNT_MARKET_UID", "EVNT_CLASSIFICATION_GROUP", "EVNT_CLASSIFICATION_SUBGROUP", "EVNT_CLASSIFICATION_ARTIFACT", "EVNT_CCDS_CHANGE_TYPE", "EVNT_SAFETY_SIGNAL_NUMBER", "EVNT_CCDS_DISTRIBUTION_DATE", "EVNT_TARGET_COMPLETION_DATE", "EVNT_GLOBAL_PRODUCT_NAME", "EVNT_GLOBAL_PRODUCT_UID", "EVNT_ASSEMBLY_ID", "EVNT_LINKED_ACTIVITY_NAME", "EVNT_LINKED_ACTIVITY_UID", "EVNT_SIGNAL_CONFIRMATION_DATE", "EVNT_ELABELLING_DATE", "EVNT_SUBMISSION_PLANNED_DATE", "EVNT_VERSION_NUMBER", "EVNT_CCDS_APPROVAL_DATE", "EVNT_SPL_SAFETY_SIGNAL_NUMBER", "REFERENCE_MARKET_NAME", "REFERENCE_MARKET_UID", "REVIEWING_MARKET_NAME", "REVIEWING_MARKET_UID", "EVNT_R_MODIFY_DATE", "EVNT_R_CREATION_DATE", "EVNT_REG_APPLICATION_NAME", "EVNT_REG_APPLICATION_UID", "EVENT_URL", "EVNT_CHANGE_DESCRIPTION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  (SELECT MGRM.R_OBJECT_ID EVNT_R_OBJECT_ID,
        MGRM.OBJECT_NAME EVNT_EVENT_NAME,
        MGRM.CONFIG_UID EVNT_CONFIG_UID,
        MGRM.FULL_DESCRIPTION EVNT_FULL_DESCRIPTION,
        SUBMGR_R.PRODUCT_FAMILY_NAME EVNT_PRODUCT_FAMILY_NAME,
        SUBMGR_R.PRODUCT_FAMILY_UID EVNT_PRODUCT_FAMILY_UID,
        SUBMGR_R.MARKET_NAME EVNT_MARKET_NAME,
        SUBMGR_R.MARKET_UID EVNT_MARKET_UID,
        MGRM.CLASSIFICATION_GROUP EVNT_CLASSIFICATION_GROUP,
        MGRM.CLASSIFICATION_SUBGROUP EVNT_CLASSIFICATION_SUBGROUP,
        MGRM.CLASSIFICATION_ARTIFACT EVNT_CLASSIFICATION_ARTIFACT,
        SUBMGR_R.CCDS_CHANGE_TYPE EVNT_CCDS_CHANGE_TYPE,
        SUBMGR_R.S_SAFETY_SIGNAL_NUMBER EVNT_SAFETY_SIGNAL_NUMBER,
        MGRM.CCDS_DISTRIBUTION_DATE EVNT_CCDS_DISTRIBUTION_DATE,
        MGRM.TARGET_COMPLETION_DATE EVNT_TARGET_COMPLETION_DATE,
        SUBMGR_R.GLOBAL_PRODUCT_NAME EVNT_GLOBAL_PRODUCT_NAME,
        SUBMGR_R.GLOBAL_PRODUCT_UID EVNT_GLOBAL_PRODUCT_UID,
        SUBMGR_R.ASSEMBLY_ID EVNT_ASSEMBLY_ID,
        SUBMGR_R.LINKED_ACTIVITY_NAME EVNT_LINKED_ACTIVITY_NAME,
        SUBMGR_R.LINKED_ACTIVITY_UID EVNT_LINKED_ACTIVITY_UID,
        SUBMGR_R.SIGNAL_CONFIRMATION_DATE EVNT_SIGNAL_CONFIRMATION_DATE,
        MGRM.EXTERNAL_APPROVAL_DATE EVNT_ELABELLING_DATE,
        (SELECT MAX (SUBMISSION_PLANNED_DATE)
           FROM COSMOSDBEXPORT.DOCUMENT a
          WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly'
                AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                AND SUBMISSION_PLANNED_DATE IS NOT NULL)
           EVNT_SUBMISSION_PLANNED_DATE,
        (SELECT MAX (VERSION_NUMBER)
           FROM COSMOSDBEXPORT.DOCUMENT a
          WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly'
                AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                AND VERSION_NUMBER IS NOT NULL)
           EVNT_VERSION_NUMBER,
        (SELECT MAX (CCDS_APPROVAL_DATE)
           FROM COSMOSDBEXPORT.DOCUMENT a
          WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly'
                AND a.R_OBJECT_ID = SUBMGR_R.ASSEMBLY_ID
                AND CCDS_APPROVAL_DATE IS NOT NULL)
           EVNT_CCDS_APPROVAL_DATE,
        SUBMGR_R.SPLITTED_SAFETY_SIGNAL_NUMBER evnt_SPL_SAFETY_SIGNAL_NUMBER,
        MGRM.REFERENCE_MARKET_NAME,
        MGRM.REFERENCE_MARKET_UID,
        MGRM.REVIEWING_MARKET_NAME,
        MGRM.REVIEWING_MARKET_UID,
        MGRM.R_MODIFY_DATE EVNT_R_MODIFY_DATE,
        MGRM.R_CREATION_DATE EVNT_R_CREATION_DATE,
        SUBMGR_R.EVNT_REG_APPLICATION_NAME EVNT_REG_APPLICATION_NAME,
        SUBMGR_R.EVNT_REG_APPLICATION_UID EVNT_REG_APPLICATION_UID,
        'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || MGRM.R_OBJECT_ID || ''    AS EVENT_URL,
        SUBMGR_R.CCDS_CHANGE_DESCRIPTION as EVNT_CHANGE_DESCRIPTION
   FROM (SELECT MGR.*
           FROM COSMOSDBEXPORT.SUBMISSION_MANAGER MGR,
                COSMOSDBEXPORT.REGULATORY_EVENT EVNT
          WHERE     MGR.R_OBJECT_ID = EVNT.R_OBJECT_ID
                AND MGR.classification_subgroup IN ('Labeling')
                AND EXISTS
                       (SELECT 1
                          FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R
                         WHERE     SUBMISSION_MANAGER_R_OBJECT_ID =
                                      MGR.R_OBJECT_ID
                               AND R_VERSION_LABEL = 'CURRENT')) MGRM,
        (SELECT *
           FROM (SELECT DISTINCT
                        SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID,
                        SUBMGR_B.PRODUCT_FAMILY_NAME,
                        SUBMGR_B.PRODUCT_FAMILY_UID,
                        SUBMGR_C.SIGNAL_CONFIRMATION_DATE,
                        SUBMGR_C.CCDS_CHANGE_TYPE,
                        SUBMGR_C.S_SAFETY_SIGNAL_NUMBER,
                        SUBMGR_B.GLOBAL_PRODUCT_NAME,
                        SUBMGR_B.GLOBAL_PRODUCT_UID,
                        SUBMGR_A.LINKED_EVENT_NAME,
                        SUBMGR_A.LINKED_EVENT_UID,
                        SUBMGR_A.MARKET_NAME,
                        SUBMGR_A.MARKET_UID,
                        SUBMGR_A.RESPONSIBLE_PERSON,
                        SUBMGR_A.RESPONSIBLE_PERSON_ID,
                        SUBMGR_A.AGENCY_RESPONSE_DATE,
                        SUBMGR_BA.ASSEMBLY_ID,
                        SUBMGR_A.LINKED_ACTIVITY_NAME,
                        SUBMGR_A.LINKED_ACTIVITY_UID,
                        SUBMGR_C.SAFETY_SIGNAL_NUMBER
                           SPLITTED_SAFETY_SIGNAL_NUMBER,
                        SUBMGR_A.REGULATORY_APPLICATION_NAME
                           EVNT_REG_APPLICATION_NAME,
                        SUBMGR_A.REGULATORY_APPLICATION_UID
                           EVNT_REG_APPLICATION_UID,
                           SUBMGR_A.CCDS_CHANGE_DESCRIPTION
                   FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_A,
                        (  SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                  MAX (ASSEMBLY_ID) ASSEMBLY_ID
                             FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_IB
                            WHERE     EXISTS
                                         (SELECT 1
                                            FROM COSMOSDBEXPORT.DOCUMENT a
                                           WHERE     CLASSIFICATION_ARTIFACT =
                                                        'Global Assembly'
                                                 AND a.R_OBJECT_ID =
                                                        SUBMGR_IB.ASSEMBLY_ID)
                                  AND ASSEMBLY_ID IS NOT NULL
                         GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID) SUBMGR_BA,
                        (  SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                  MAX (PRODUCT_FAMILY_NAME) PRODUCT_FAMILY_NAME,
                                  MAX (PRODUCT_FAMILY_UID) PRODUCT_FAMILY_UID,
                                  MAX (GLOBAL_PRODUCT_NAME) GLOBAL_PRODUCT_NAME,
                                  MAX (GLOBAL_PRODUCT_UID) GLOBAL_PRODUCT_UID
                             FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_B
                            WHERE PRODUCT_FAMILY_NAME IS NOT NULL
                         GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID) SUBMGR_B,
                        (SELECT DISTINCT SUBMISSION_MANAGER_R_OBJECT_ID,
                                         ---R_INDEX,
                                         COL1 SAFETY_SIGNAL_NUMBER, /*
                                          CCDS_CHANGE_DESCRIPTION,*/
                                         SIGNAL_CONFIRMATION_DATE,
                                         ---CCDS_CHANGE_IMPLEMENTATION,
                                         CCDS_CHANGE_TYPE,
                                         /*CHANGE_NUMBER,
                                         IS_CCDS,*/
                                         S_SAFETY_SIGNAL_NUMBER
                           FROM (SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                        R_INDEX,
                                        COL1,
                                        CCDS_CHANGE_DESCRIPTION,
                                        SIGNAL_CONFIRMATION_DATE,
                                        CCDS_CHANGE_IMPLEMENTATION,
                                        CCDS_CHANGE_TYPE,
                                        CHANGE_NUMBER,
                                        IS_CCDS,
                                        S_SAFETY_SIGNAL_NUMBER
                                   FROM (WITH Q_STR
                                                 AS (SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                                            R_INDEX,
                                                            REPLACE (
                                                               SAFETY_SIGNAL_NUMBER,
                                                               '|',
                                                               ';')
                                                               str,
                                                            CCDS_CHANGE_DESCRIPTION,
                                                            SIGNAL_CONFIRMATION_DATE,
                                                            CCDS_CHANGE_IMPLEMENTATION,
                                                            CCDS_CHANGE_TYPE,
                                                            CHANGE_NUMBER,
                                                            IS_CCDS
                                                       FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R
                                                      WHERE ---SUBMISSION_MANAGER_R_OBJECT_ID='0800f9f685f91534' and
                                                            CCDS_CHANGE_TYPE
                                                               IS NOT NULL)
                                         SELECT DISTINCT
                                                SUBMISSION_MANAGER_R_OBJECT_ID,
                                                R_INDEX,
                                                TRIM (COLUMN_VALUE) COL1,
                                                CCDS_CHANGE_DESCRIPTION,
                                                SIGNAL_CONFIRMATION_DATE,
                                                CCDS_CHANGE_IMPLEMENTATION,
                                                CCDS_CHANGE_TYPE,
                                                CHANGE_NUMBER,
                                                IS_CCDS,
                                                str S_SAFETY_SIGNAL_NUMBER
                                           FROM Q_STR,
                                                XMLTABLE (
                                                   (   '"'
                                                    || REPLACE (STR,
                                                                ';',
                                                                '","')
                                                    || '"')))
                                 UNION
                                 SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                                        R_INDEX,
                                        SAFETY_SIGNAL_NUMBER COL1,
                                        CCDS_CHANGE_DESCRIPTION,
                                        SIGNAL_CONFIRMATION_DATE,
                                        CCDS_CHANGE_IMPLEMENTATION,
                                        CCDS_CHANGE_TYPE,
                                        CHANGE_NUMBER,
                                        IS_CCDS,
                                        SAFETY_SIGNAL_NUMBER
                                           S_SAFETY_SIGNAL_NUMBER
                                   FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R
                                  WHERE     CCDS_CHANGE_TYPE IS NOT NULL
                                        AND SAFETY_SIGNAL_NUMBER IS NULL
                                        AND 1 = 2)) SUBMGR_C
                  WHERE     SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_B.SUBMISSION_MANAGER_R_OBJECT_ID
                        AND SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_BA.SUBMISSION_MANAGER_R_OBJECT_ID(+)
                        AND SUBMGR_A.SUBMISSION_MANAGER_R_OBJECT_ID =
                               SUBMGR_C.SUBMISSION_MANAGER_R_OBJECT_ID)
          WHERE MARKET_NAME IS NOT NULL) SUBMGR_R
  WHERE MGRM.R_OBJECT_ID = SUBMGR_R.SUBMISSION_MANAGER_R_OBJECT_ID);


--VW_ACT_F6

  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_ACT_F6" ("ACT_R_OBJECT_ID", "ACT_NAME", "ACT_CONFIG_UID", "ACT_FULL_DESCRIPTION", "ACT_PRODUCT_FAMILY_NAME", "ACT_PRODUCT_FAMILY_UID", "ACT_CLASSIFICATION_GROUP", "ACT_CLASSIFICATION_SUBGROUP", "ACT_CLASSIFICATION_ARTIFACT", "ACT_CCDS_DISTRIBUTION_DATE", "ACT_TARGET_COMPLETION_DATE", "ACT_ELABELLING_DATE", "ACT_IS_ELABELLING_IMPACTD", "ACT_SUBMISSION_PLANNED_DATE", "ACT_FIRST_SUBMISSION_DATE", "ACT_AGENCY_APPROVAL_DATE", "ACT_AGENCY_APPROVAL_STATUS", "ACT_R_MODIFY_DATE", "ACT_R_CREATION_DATE", "ACT_REG_APPLICATION_NAME", "ACT_REG_APPLICATION_UID", "ACT_MEDICINAL_PRODUCT_NAME", "ACT_MEDICINAL_PRODUCT_UID", "ACT_REVIEWING_MARKET_NAME", "ACT_REVIEWING_MARKET_UID", "ACTIVITY_URL", "ACT_CHANGE_DESCRIPTION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  (SELECT DISTINCT
            MGR.R_OBJECT_ID
                ACT_R_OBJECT_ID,
            MGR.OBJECT_NAME
                ACT_NAME,
            MGR.CONFIG_UID
                ACT_CONFIG_UID,
            MGR.FULL_DESCRIPTION
                ACT_FULL_DESCRIPTION,
            SUBMGR_B.PRODUCT_FAMILY_NAME
                ACT_PRODUCT_FAMILY_NAME,
            SUBMGR_B.PRODUCT_FAMILY_UID
                ACT_PRODUCT_FAMILY_UID,
            MGR.CLASSIFICATION_GROUP
                ACT_CLASSIFICATION_GROUP,
            MGR.CLASSIFICATION_SUBGROUP
                ACT_CLASSIFICATION_SUBGROUP,
            MGR.CLASSIFICATION_ARTIFACT
                ACT_CLASSIFICATION_ARTIFACT,
            MGR.CCDS_DISTRIBUTION_DATE
                ACT_CCDS_DISTRIBUTION_DATE,
            MGR.TARGET_COMPLETION_DATE
                ACT_TARGET_COMPLETION_DATE,
            MGR.EXTERNAL_APPROVAL_DATE
                ACT_ELABELLING_DATE,
            MGR.IS_REG_LABELING_IMPACTED
                ACT_IS_ELABELLING_IMPACTD,
            (SELECT MAX (SUBMISSION_PLANNED_DATE)
               FROM COSMOSDBEXPORT.DOCUMENT a
              WHERE     CLASSIFICATION_ARTIFACT = 'Global Assembly'
                    AND a.R_OBJECT_ID = SUBMGR_RR.ASSEMBLY_ID
                    AND SUBMISSION_PLANNED_DATE IS NOT NULL)
                ACT_SUBMISSION_PLANNED_DATE,
            MGR.FIRST_SUBMISSION_DATE
                ACT_FIRST_SUBMISSION_DATE,
            MGR.AGENCY_APPROVAL_DATE
                ACT_AGENCY_APPROVAL_DATE,
            MGR.AGENCY_APPROVAL_STATUS
                ACT_AGENCY_APPROVAL_STATUS,
            MGR.R_MODIFY_DATE
                ACT_R_MODIFY_DATE,
            MGR.R_CREATION_DATE
                ACT_R_CREATION_DATE,
            SUBMGR_B.REGULATORY_APPLICATION_NAME
                ACT_REG_APPLICATION_NAME,
            SUBMGR_B.REGULATORY_APPLICATION_UID
                ACT_REG_APPLICATION_UID,
            SUBMGR_B.MEDICINAL_PRODUCT_NAME
                ACT_MEDICINAL_PRODUCT_NAME,
            SUBMGR_B.MEDICINAL_PRODUCT_UID
                ACT_MEDICINAL_PRODUCT_UID,
            MGR.REVIEWING_MARKET_NAME
                ACT_REVIEWING_MARKET_NAME,
            MGR.REVIEWING_MARKET_UID
                ACT_REVIEWING_MARKET_UID, 
                'https://cosmos-dev1.abbvienet.com/cosmos-new/drl/objectId/' || MGR.R_OBJECT_ID || ''  AS ACTIVITY_URL,
SUBMGR_RR.CCDS_CHANGE_DESCRIPTION ACT_CHANGE_DESCRIPTION

       FROM COSMOSDBEXPORT.SUBMISSION_MANAGER    MGR,
            COSMOSDBEXPORT.REGULATORY_ACTIVITY   ACT,
            COSMOSDBEXPORT.SUBMISSION_MANAGER_R  SUBMGR_RR,
            (  SELECT SUBMISSION_MANAGER_R_OBJECT_ID,
                      MAX (PRODUCT_FAMILY_NAME)
                          PRODUCT_FAMILY_NAME,
                      MAX (PRODUCT_FAMILY_UID)
                          PRODUCT_FAMILY_UID,
                      MAX (REGULATORY_APPLICATION_NAME)
                          REGULATORY_APPLICATION_NAME,
                      MAX (REGULATORY_APPLICATION_UID)
                          REGULATORY_APPLICATION_UID,
                      MAX (MEDICINAL_PRODUCT_NAME)
                          MEDICINAL_PRODUCT_NAME,
                      MAX (MEDICINAL_PRODUCT_UID)
                          MEDICINAL_PRODUCT_UID
                 FROM COSMOSDBEXPORT.SUBMISSION_MANAGER_R SUBMGR_B
                WHERE PRODUCT_FAMILY_NAME IS NOT NULL
             GROUP BY SUBMISSION_MANAGER_R_OBJECT_ID) SUBMGR_B
      WHERE     MGR.R_OBJECT_ID = ACT.R_OBJECT_ID
            AND MGR.R_OBJECT_ID = SUBMGR_B.SUBMISSION_MANAGER_R_OBJECT_ID
            AND MGR.R_OBJECT_ID = SUBMGR_RR.SUBMISSION_MANAGER_R_OBJECT_ID);




--VW_PSMF_R6


  CREATE OR REPLACE FORCE EDITIONABLE VIEW "SVC_HUBBLE"."VW_PSMF_R6" ("BS_ACT_ID", "BS_EVNT_UID", "EVNT_R_OBJECT_ID", "EVNT_EVENT_NAME", "EVNT_CONFIG_UID", "EVNT_FULL_DESCRIPTION", "EVNT_PRODUCT_FAMILY_NAME", "EVNT_PRODUCT_FAMILY_UID", "EVNT_MARKET_NAME", "EVNT_MARKET_UID", "EVNT_CLASSIFICATION_GROUP", "EVNT_CLASSIFICATION_SUBGROUP", "EVNT_CLASSIFICATION_ARTIFACT", "EVNT_CCDS_CHANGE_TYPE", "EVNT_SAFETY_SIGNAL_NUMBER", "EVNT_CCDS_DISTRIBUTION_DATE", "EVNT_TARGET_COMPLETION_DATE", "EVNT_GLOBAL_PRODUCT_NAME", "EVNT_ASSEMBLY_ID", "EVNT_LINKED_ACTIVITY_NAME", "EVNT_LINKED_ACTIVITY_UID", "EVNT_SIGNAL_CONFIRMATION_DATE", "EVNT_ELABELLING_DATE", "EVNT_SUBMISSION_PLANNED_DATE", "EVNT_VERSION_NUMBER", "EVNT_CCDS_APPROVAL_DATE", "EVNT_SPL_SAFETY_SIGNAL_NUMBER", "EVNT_R_MODIFY_DATE", "EVNT_R_CREATION_DATE", "ACT_R_OBJECT_ID", "ACT_NAME", "ACT_CONFIG_UID", "ACT_FULL_DESCRIPTION", "ACT_PRODUCT_FAMILY_NAME", "ACT_PRODUCT_FAMILY_UID", "ACT_CLASSIFICATION_GROUP", "ACT_CLASSIFICATION_SUBGROUP", "ACT_CLASSIFICATION_ARTIFACT", "ACT_CCDS_DISTRIBUTION_DATE", "ACT_TARGET_COMPLETION_DATE", "ACT_ELABELLING_DATE", "ACT_IS_ELABELLING_IMPACTD", "ACT_SUBMISSION_PLANNED_DATE", "ACT_FIRST_SUBMISSION_DATE", "ACT_AGENCY_APPROVAL_DATE", "ACT_AGENCY_APPROVAL_STATUS", "ACT_R_MODIFY_DATE", "ACT_R_CREATION_DATE", "ACT_REG_APPLICATION_NAME", "ACT_REG_APPLICATION_UID", "ACT_MEDICINAL_PRODUCT_NAME", "ACT_MEDICINAL_PRODUCT_UID", "ROSTER_REGION", "EVENT_URL", "ACTIVITY_URL", "EVNT_CHANGE_DESCRIPTION", "ACT_CHANGE_DESCRIPTION") DEFAULT COLLATION "USING_NLS_COMP"  AS 
  SELECT DISTINCT 	 trim(ACT_MAIN."BS_ACT_ID") BS_ACT_ID,
                     trim(ACT_MAIN."BS_EVNT_UID") BS_EVNT_UID,
                     trim(EVNT_R_OBJECT_ID) EVNT_R_OBJECT_ID,
                     trim(EVNT_EVENT_NAME) EVNT_EVENT_NAME,
                     trim(EVNT_CONFIG_UID) EVNT_CONFIG_UID,
                     trim(EVNT_FULL_DESCRIPTION) EVNT_FULL_DESCRIPTION,
                     trim(EVNT_PRODUCT_FAMILY_NAME) EVNT_PRODUCT_FAMILY_NAME,
                     trim(EVNT_PRODUCT_FAMILY_UID) EVNT_PRODUCT_FAMILY_UID,
                     trim(EVNT_MARKET_NAME) EVNT_MARKET_NAME,
                     trim(EVNT_MARKET_UID) EVNT_MARKET_UID,
                     trim(EVNT_CLASSIFICATION_GROUP) EVNT_CLASSIFICATION_GROUP,
                     trim(EVNT_CLASSIFICATION_SUBGROUP) EVNT_CLASSIFICATION_SUBGROUP,
                     trim(EVNT_CLASSIFICATION_ARTIFACT) EVNT_CLASSIFICATION_ARTIFACT,
                     trim(EVNT_CCDS_CHANGE_TYPE) EVNT_CCDS_CHANGE_TYPE,
                     trim(EVNT_SAFETY_SIGNAL_NUMBER) EVNT_SAFETY_SIGNAL_NUMBER,
                     trim(EVNT_CCDS_DISTRIBUTION_DATE) EVNT_CCDS_DISTRIBUTION_DATE,
                     trim(EVNT_TARGET_COMPLETION_DATE) EVNT_TARGET_COMPLETION_DATE,
                     trim(EVNT_GLOBAL_PRODUCT_NAME) EVNT_GLOBAL_PRODUCT_NAME,
                     trim(EVNT_ASSEMBLY_ID) EVNT_ASSEMBLY_ID,
                     trim(EVNT_LINKED_ACTIVITY_NAME) EVNT_LINKED_ACTIVITY_NAME,
                     trim(EVNT_LINKED_ACTIVITY_UID) EVNT_LINKED_ACTIVITY_UID,
                     trim(EVNT_SIGNAL_CONFIRMATION_DATE) EVNT_SIGNAL_CONFIRMATION_DATE,
                     trim(EVNT_ELABELLING_DATE) EVNT_ELABELLING_DATE,
                     trim(EVNT_SUBMISSION_PLANNED_DATE) EVNT_SUBMISSION_PLANNED_DATE,
                     trim(EVNT_VERSION_NUMBER) EVNT_VERSION_NUMBER,
                     trim(EVNT_CCDS_APPROVAL_DATE) EVNT_CCDS_APPROVAL_DATE,
                     trim(evnt_SPL_SAFETY_SIGNAL_NUMBER) evnt_SPL_SAFETY_SIGNAL_NUMBER,
                     trim(EVNT_R_MODIFY_DATE) EVNT_R_MODIFY_DATE,
                     trim(EVNT_R_CREATION_DATE) EVNT_R_CREATION_DATE,
                     trim(ACT_MAIN."ACT_R_OBJECT_ID") ACT_R_OBJECT_ID,
                     trim(ACT_MAIN."ACT_NAME") ACT_NAME,
                     trim(ACT_MAIN."ACT_CONFIG_UID") ACT_CONFIG_UID,
                     trim(ACT_MAIN."ACT_FULL_DESCRIPTION") ACT_FULL_DESCRIPTION,
                     trim(ACT_MAIN."ACT_PRODUCT_FAMILY_NAME")ACT_PRODUCT_FAMILY_NAME,
                     trim(ACT_MAIN."ACT_PRODUCT_FAMILY_UID")ACT_PRODUCT_FAMILY_UID,
                     trim(ACT_MAIN."ACT_CLASSIFICATION_GROUP")ACT_CLASSIFICATION_GROUP,
                     trim(ACT_MAIN."ACT_CLASSIFICATION_SUBGROUP")ACT_CLASSIFICATION_SUBGROUP,
                     trim(ACT_MAIN."ACT_CLASSIFICATION_ARTIFACT")ACT_CLASSIFICATION_ARTIFACT,
                     trim(ACT_MAIN."ACT_CCDS_DISTRIBUTION_DATE")ACT_CCDS_DISTRIBUTION_DATE,
                     trim(ACT_MAIN."ACT_TARGET_COMPLETION_DATE")ACT_TARGET_COMPLETION_DATE,
                     trim(ACT_MAIN."ACT_ELABELLING_DATE")ACT_ELABELLING_DATE,
                     trim(ACT_MAIN."ACT_IS_ELABELLING_IMPACTD")ACT_IS_ELABELLING_IMPACTD,
                     trim(ACT_MAIN."ACT_SUBMISSION_PLANNED_DATE")ACT_SUBMISSION_PLANNED_DATE,
                     trim(ACT_MAIN."ACT_FIRST_SUBMISSION_DATE")ACT_FIRST_SUBMISSION_DATE,
                     trim(ACT_MAIN."ACT_AGENCY_APPROVAL_DATE")ACT_AGENCY_APPROVAL_DATE,
                     trim(ACT_MAIN."ACT_AGENCY_APPROVAL_STATUS")ACT_AGENCY_APPROVAL_STATUS,
                     trim(ACT_MAIN.ACT_R_MODIFY_DATE)ACT_R_MODIFY_DATE,
                     trim(ACT_MAIN.ACT_R_CREATION_DATE)ACT_R_CREATION_DATE,
                     trim(ACT_MAIN.ACT_REG_APPLICATION_NAME)ACT_REG_APPLICATION_NAME,
                     trim(ACT_MAIN.ACT_REG_APPLICATION_UID)ACT_REG_APPLICATION_UID,
                     trim(ACT_MAIN.ACT_MEDICINAL_PRODUCT_NAME)ACT_MEDICINAL_PRODUCT_NAME,
                     trim(ACT_MAIN.ACT_MEDICINAL_PRODUCT_UID)ACT_MEDICINAL_PRODUCT_UID,
					 m.roster_region,
                 evnt_o.EVENT_URL,
                     ACT_MAIN.ACTIVITY_URL,trim(evnt_o.evnt_change_description) as evnt_change_description ,trim(act_main.act_change_description) act_change_description
       FROM VW_EVENT_F6  evnt_o,
            (SELECT BS_ACT_ID, BS_EVNT_UID, ACT.*
               FROM VW_ACT_F6 ACT, VW_label_lnkg ACT_LNKG
              WHERE ACT.ACT_R_OBJECT_ID = ACT_LNKG.BS_ACT_ID) ACT_MAIN, cosmosdbexport.market m
      WHERE     evnt_o.EVNT_CONFIG_UID = ACT_MAIN.BS_EVNT_UID(+)
            AND EVNT_MARKET_NAME = ACT_REVIEWING_MARKET_NAME(+)
            And EVNT_MARKET_NAME  =  m.iso_country_name(+);
